#!/bin/sh
case "$1" in
  start)
	printf "Starting network (udhcpc): "
	udhcpc >> /var/log/udhcpc.log 2>&1
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping network (udhcpc): "
	killall udhcpc
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

