LINUX_FTPM_MOD_EXT_VERSION = 1.0
LINUX_FTPM_MOD_EXT_SOURCE = local
LINUX_FTPM_MOD_EXT_SITE = $(BR2_PACKAGE_LINUX_FTPM_MOD_EXT_SITE)
LINUX_FTPM_MOD_EXT_PATH = $(BR2_PACKAGE_LINUX_FTPM_MOD_EXT_PATH)
LINUX_FTPM_MOD_EXT_SITE_METHOD = local
LINUX_FTPM_MOD_EXT_INSTALL_DIR=$(TARGET_DIR)/lib/modules/extra

# Avoid CMake warnings on these unused variables set by Buildroot
LINUX_FTPM_MOD_EXT_CONF_OPTS += -DBUILD_DOC=OFF -DBUILD_DOCS=OFF \
				-DBUILD_EXAMPLE=OFF -DBUILD_EXAMPLES=OFF \
				-DBUILD_TEST=OFF -DBUILD_TESTING=OFF \
				-DBUILD_TESTS=OFF

define LINUX_FTPM_MOD_EXT_INSTALL
	echo "Installing TPM kernel module" && \
		mkdir -p $(LINUX_FTPM_MOD_EXT_INSTALL_DIR)
		$(INSTALL) -v -p --mode=444 \
		--target-directory=$(LINUX_FTPM_MOD_EXT_INSTALL_DIR) \
		$(LINUX_FTPM_MOD_EXT_PATH)/drivers/char/tpm/tpm_ftpm_tee.ko
endef

LINUX_FTPM_MOD_EXT_POST_INSTALL_TARGET_HOOKS += LINUX_FTPM_MOD_EXT_INSTALL

$(eval $(cmake-package))
