#!/bin/sh
#
# /etc/init.d/optee
#
# Start/stop tee-supplicant (OP-TEE normal world daemon)
#
case "$1" in
    start)
	if [ -e /usr/sbin/tee-supplicant -a -e /dev/teepriv0 ]; then
		printf "Starting tee-supplicant... "
		/usr/sbin/tee-supplicant -d
		[ $? = 0 ] && echo "OK" || echo "FAIL"
	else
		echo "tee-supplicant or TEE device not found"
		exit 1
	fi

        ;;
    stop)
	killall tee-supplicant
	;;
    status)
	cat /dev/teepriv0 2>&1 | grep -q "Device or resource busy" || not="not "
	echo "tee-supplicant is ${not}active"
	;;
esac
