OPTEE_TEST_VERSION = 1.0
OPTEE_TEST_SOURCE = local
OPTEE_TEST_SITE = $(BR2_PACKAGE_OPTEE_TEST_SITE)
OPTEE_TEST_SITE_METHOD = local
OPTEE_TEST_INSTALL_STAGING = YES
OPTEE_TEST_DEPENDENCIES = optee_client openssl host-python-pycrypto
OPTEE_TEST_SDK = $(BR2_PACKAGE_OPTEE_TEST_SDK)
OPTEE_TEST_CONF_OPTS = -DOPTEE_TEST_SDK=$(OPTEE_TEST_SDK)

$(eval $(cmake-package))
