VERAISON_RUST_APICLIENT_VERSION = 3fef382
VERAISON_RUST_APICLIENT_SITE = $(call github,veraison,rust-apiclient,v$(VERAISON_RUST_APICLIENT_VERSION))
VERAISON_RUST_APICLIENT_DEPENDENCIES = optee_client_ext openssl
VERAISON_RUST_APICLIENT_LICENSE = Apache-2.0
VERAISON_RUST_APICLIENT_LICENSE_FILES = LICENSE

$(eval $(cargo-package))
