VERAISON_RUST_APICLIENT_EXT_VERSION = 3fef382ad58465c5b6b3ad779d51d8035e3b0459
VERAISON_RUST_APICLIENT_EXT_SITE = https://github.com/veraison/rust-apiclient.git
VERAISON_RUST_APICLIENT_EXT_SITE_METHOD = git
VERAISON_RUST_APICLIENT_EXT_DEPENDENCIES = optee_client_ext openssl
VERAISON_RUST_APICLIENT_EXT_LICENSE = Apache-2.0
VERAISON_RUST_APICLIENT_EXT_LICENSE_FILES = LICENSE

$(eval $(cargo-package))
