CONFIG_SPL_OPTEE_LOAD_ADDR=0xf1000000
CONFIG_TEE=y
CONFIG_OPTEE=y
CONFIG_OPTEE_LIB=y
CONFIG_OPTEE_TZDRAM_SIZE=0x0
CONFIG_RNG_OPTEE=y
CONFIG_CMD_RNG=y
CONFIG_SPL_SYS_MALLOC_SIZE=0x0200000
CONFIG_SPL_OPENSBI_SCRATCH_OPTIONS=0x0
